# Generated by Django 3.0.3 on 2020-09-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('amount_Transferd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('currentCredit', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='trans_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='creditApp.User_table'),
        ),
        migrations.AddField(
            model_name='transaction_table',
            name='trans_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='creditApp.User_table'),
        ),
    ]
