# Generated by Django 3.0.3 on 2020-09-16 03:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creditApp', '0002_auto_20200914_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction_table',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
