# Generated by Django 3.0.3 on 2020-09-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditApp', '0003_auto_20200916_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
