# Generated by Django 3.0.3 on 2020-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditApp', '0004_auto_20200916_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_table',
            name='amount_Transferd',
            field=models.PositiveIntegerField(),
        ),
    ]
